// Mock data for the application
import {
  Heart, Sun, Baby, Brain, Stethoscope, Bone, Eye, Sparkles,
  Users, FileCheck, Star as StarIcon, Award,
  ClipboardList, Smartphone, Building2, Pill,
} from 'lucide-react';

export const doctors = [
  {
    id: 1,
    name: 'Dra. María González',
    specialty: 'Cardiología',
    rating: 4.9,
    reviews: 127,
    location: 'Ciudad de México',
    price: '$800 MXN',
    available: true,
    experience: '15 años',
    tags: ['Hipertensión', 'Arritmias', 'Check-up'],
    bio: 'Cardióloga certificada con más de 15 años de experiencia en el diagnóstico y tratamiento de enfermedades cardiovasculares.',
    education: 'UNAM — Facultad de Medicina',
    nextAvailable: 'Hoy, 3:00 PM',
  },
  {
    id: 2,
    name: 'Dr. Carlos Ramírez',
    specialty: 'Dermatología',
    rating: 4.8,
    reviews: 98,
    location: 'Guadalajara',
    price: '$650 MXN',
    available: true,
    experience: '12 años',
    tags: ['Acné', 'Dermatitis', 'Estética'],
    bio: 'Especialista en dermatología clínica y estética con enfoque en tratamientos personalizados.',
    education: 'ITESM — Escuela de Medicina',
    nextAvailable: 'Mañana, 10:00 AM',
  },
  {
    id: 3,
    name: 'Dra. Ana Martínez',
    specialty: 'Pediatría',
    rating: 4.9,
    reviews: 203,
    location: 'Monterrey',
    price: '$700 MXN',
    available: true,
    experience: '18 años',
    tags: ['Neonatología', 'Vacunación', 'Desarrollo'],
    bio: 'Pediatra con especialidad en neonatología y desarrollo infantil.',
    education: 'Universidad de Monterrey',
    nextAvailable: 'Hoy, 5:00 PM',
  },
  {
    id: 4,
    name: 'Dr. Roberto Silva',
    specialty: 'Neurología',
    rating: 4.7,
    reviews: 85,
    location: 'Ciudad de México',
    price: '$950 MXN',
    available: false,
    experience: '20 años',
    tags: ['Migraña', 'Epilepsia', 'Neurorehabilitación'],
    bio: 'Neurólogo especializado en trastornos del movimiento y neurorehabilitación.',
    education: 'UANL — Facultad de Medicina',
    nextAvailable: 'Viernes, 9:00 AM',
  },
  {
    id: 5,
    name: 'Dra. Laura Herrera',
    specialty: 'Ginecología',
    rating: 4.9,
    reviews: 156,
    location: 'Puebla',
    price: '$750 MXN',
    available: true,
    experience: '14 años',
    tags: ['Embarazo', 'Menopausia', 'Fertilidad'],
    bio: 'Ginecóloga y obstetra con enfoque en salud reproductiva integral.',
    education: 'BUAP — Facultad de Medicina',
    nextAvailable: 'Hoy, 4:30 PM',
  },
  {
    id: 6,
    name: 'Dr. Fernando López',
    specialty: 'Traumatología',
    rating: 4.6,
    reviews: 74,
    location: 'Guadalajara',
    price: '$850 MXN',
    available: true,
    experience: '10 años',
    tags: ['Fracturas', 'Artroscopia', 'Rehabilitación'],
    bio: 'Traumatólogo deportivo con experiencia en lesiones musculoesqueléticas.',
    education: 'UDG — Centro Universitario de Ciencias de la Salud',
    nextAvailable: 'Mañana, 11:00 AM',
  },
];

export const specialties = [
  { name: 'Cardiología', icon: Heart, count: 24, color: 'rose' },
  { name: 'Dermatología', icon: Sun, count: 18, color: 'amber' },
  { name: 'Pediatría', icon: Baby, count: 31, color: 'cyan' },
  { name: 'Neurología', icon: Brain, count: 15, color: 'purple' },
  { name: 'Ginecología', icon: Stethoscope, count: 22, color: 'emerald' },
  { name: 'Traumatología', icon: Bone, count: 12, color: 'blue' },
  { name: 'Oftalmología', icon: Eye, count: 16, color: 'cyan' },
  { name: 'Psiquiatría', icon: Sparkles, count: 19, color: 'purple' },
];

export const testimonials = [
  {
    name: 'Andrea Ruiz',
    role: 'Paciente desde 2024',
    text: 'MediFlow cambió completamente mi experiencia médica. Pude agendar con mi cardióloga en menos de 2 minutos y la consulta fue excelente.',
    rating: 5,
  },
  {
    name: 'Miguel Torres',
    role: 'Paciente desde 2025',
    text: 'La plataforma es increíblemente intuitiva. Me encanta poder ver el historial de mis citas y los diagnósticos de forma organizada.',
    rating: 5,
  },
  {
    name: 'Carmen Díaz',
    role: 'Paciente desde 2024',
    text: 'Encontré al mejor dermatólogo gracias a las reseñas. El sistema de agenda es muy eficiente y nunca he tenido que esperar.',
    rating: 4,
  },
  {
    name: 'Dr. José Mendoza',
    role: 'Médico verificado',
    text: 'Como médico, MediFlow me ha ayudado a gestionar mis citas de manera profesional. La plataforma es excelente tanto para doctores como pacientes.',
    rating: 5,
  },
];

export const stats = [
  { value: '2,500+', label: 'Médicos Certificados', icon: Users },
  { value: '50,000+', label: 'Consultas Realizadas', icon: FileCheck },
  { value: '4.8', label: 'Rating Promedio', icon: StarIcon },
  { value: '98%', label: 'Pacientes Satisfechos', icon: Award },
];

export const services = [
  {
    icon: Stethoscope,
    title: 'Consulta General',
    description: 'Atención médica integral para diagnóstico y tratamiento de enfermedades comunes.',
    color: 'blue',
  },
  {
    icon: Brain,
    title: 'Consulta Especializada',
    description: 'Accede a especialistas en cardiología, neurología, dermatología y más.',
    color: 'purple',
  },
  {
    icon: Smartphone,
    title: 'Telemedicina',
    description: 'Consultas en línea desde la comodidad de tu hogar, disponibles 24/7.',
    color: 'cyan',
  },
  {
    icon: Building2,
    title: 'Urgencias',
    description: 'Atención inmediata para casos urgentes con médicos de guardia.',
    color: 'rose',
  },
  {
    icon: Pill,
    title: 'Recetas Digitales',
    description: 'Recibe tus recetas médicas de forma digital, listas para surtir.',
    color: 'emerald',
  },
  {
    icon: ClipboardList,
    title: 'Historial Clínico',
    description: 'Tu expediente médico completo y seguro, accesible en cualquier momento.',
    color: 'amber',
  },
];

export const appointments = [
  {
    id: 1,
    doctor: 'Dra. María González',
    specialty: 'Cardiología',
    date: '2026-03-05',
    time: '10:00 AM',
    status: 'confirmed',
    type: 'Presencial',
  },
  {
    id: 2,
    doctor: 'Dr. Carlos Ramírez',
    specialty: 'Dermatología',
    date: '2026-03-08',
    time: '3:30 PM',
    status: 'pending',
    type: 'Telemedicina',
  },
  {
    id: 3,
    doctor: 'Dra. Ana Martínez',
    specialty: 'Pediatría',
    date: '2026-02-28',
    time: '11:00 AM',
    status: 'completed',
    type: 'Presencial',
  },
];
