// Mock data for the application
import {
  Heart, Sun, Baby, Brain, Stethoscope, Bone, Eye, Sparkles,
  Users, FileCheck, Star as StarIcon, Award,
  ClipboardList, Smartphone, Building2, Pill,
  MapPin, Clock, Phone, Shield, Truck, CreditCard,
  FileText, Syringe, Thermometer, Activity,
} from 'lucide-react';

export const doctors = [
  {
    id: 1,
    name: 'Dra. María González',
    specialty: 'Cardiología',
    rating: 4.9,
    reviews: 127,
    location: 'Santo Domingo',
    price: 'RD$ 2,500',
    available: true,
    experience: '15 años',
    tags: ['Hipertensión', 'Arritmias', 'Check-up'],
    bio: 'Cardióloga certificada con más de 15 años de experiencia en el diagnóstico y tratamiento de enfermedades cardiovasculares.',
    education: 'UNPHU — Facultad de Medicina',
    nextAvailable: 'Hoy, 3:00 PM',
  },
  {
    id: 2,
    name: 'Dr. Carlos Ramírez',
    specialty: 'Dermatología',
    rating: 4.8,
    reviews: 98,
    location: 'Santiago de los Caballeros',
    price: 'RD$ 2,000',
    available: true,
    experience: '12 años',
    tags: ['Acné', 'Dermatitis', 'Estética'],
    bio: 'Especialista en dermatología clínica y estética con enfoque en tratamientos personalizados.',
    education: 'PUCMM — Facultad de Medicina',
    nextAvailable: 'Mañana, 10:00 AM',
  },
  {
    id: 3,
    name: 'Dra. Ana Martínez',
    specialty: 'Pediatría',
    rating: 4.9,
    reviews: 203,
    location: 'Punta Cana',
    price: 'RD$ 2,200',
    available: true,
    experience: '18 años',
    tags: ['Neonatología', 'Vacunación', 'Desarrollo'],
    bio: 'Pediatra con especialidad en neonatología y desarrollo infantil.',
    education: 'UASD — Facultad de Ciencias de la Salud',
    nextAvailable: 'Hoy, 5:00 PM',
  },
  {
    id: 4,
    name: 'Dr. Roberto Silva',
    specialty: 'Neurología',
    rating: 4.7,
    reviews: 85,
    location: 'Santo Domingo',
    price: 'RD$ 3,000',
    available: false,
    experience: '20 años',
    tags: ['Migraña', 'Epilepsia', 'Neurorehabilitación'],
    bio: 'Neurólogo especializado en trastornos del movimiento y neurorehabilitación.',
    education: 'INTEC — Área de Ciencias de la Salud',
    nextAvailable: 'Viernes, 9:00 AM',
  },
  {
    id: 5,
    name: 'Dra. Laura Herrera',
    specialty: 'Ginecología',
    rating: 4.9,
    reviews: 156,
    location: 'La Romana',
    price: 'RD$ 2,300',
    available: true,
    experience: '14 años',
    tags: ['Embarazo', 'Menopausia', 'Fertilidad'],
    bio: 'Ginecóloga y obstetra con enfoque en salud reproductiva integral.',
    education: 'UCSD — Facultad de Medicina',
    nextAvailable: 'Hoy, 4:30 PM',
  },
  {
    id: 6,
    name: 'Dr. Fernando López',
    specialty: 'Traumatología',
    rating: 4.6,
    reviews: 74,
    location: 'Santiago de los Caballeros',
    price: 'RD$ 2,800',
    available: true,
    experience: '10 años',
    tags: ['Fracturas', 'Artroscopia', 'Rehabilitación'],
    bio: 'Traumatólogo deportivo con experiencia en lesiones musculoesqueléticas.',
    education: 'PUCMM — Facultad de Ciencias de la Salud',
    nextAvailable: 'Mañana, 11:00 AM',
  },
];

export const specialties = [
  { name: 'Cardiología', icon: Heart, count: 24, color: 'rose' },
  { name: 'Dermatología', icon: Sun, count: 18, color: 'amber' },
  { name: 'Pediatría', icon: Baby, count: 31, color: 'cyan' },
  { name: 'Neurología', icon: Brain, count: 15, color: 'purple' },
  { name: 'Ginecología', icon: Stethoscope, count: 22, color: 'emerald' },
  { name: 'Traumatología', icon: Bone, count: 12, color: 'blue' },
  { name: 'Oftalmología', icon: Eye, count: 16, color: 'cyan' },
  { name: 'Psiquiatría', icon: Sparkles, count: 19, color: 'purple' },
];

export const testimonials = [
  {
    name: 'Andrea Ruiz',
    role: 'Paciente desde 2024',
    text: 'MediFlow cambió completamente mi experiencia médica. Pude agendar con mi cardióloga en menos de 2 minutos y la consulta fue excelente.',
    rating: 5,
  },
  {
    name: 'Miguel Torres',
    role: 'Paciente desde 2025',
    text: 'La plataforma es increíblemente intuitiva. Me encanta poder ver el historial de mis citas y los diagnósticos de forma organizada.',
    rating: 5,
  },
  {
    name: 'Carmen Díaz',
    role: 'Paciente desde 2024',
    text: 'Encontré al mejor dermatólogo gracias a las reseñas. El sistema de agenda es muy eficiente y nunca he tenido que esperar.',
    rating: 4,
  },
  {
    name: 'Dr. José Mendoza',
    role: 'Médico verificado',
    text: 'Como médico, MediFlow me ha ayudado a gestionar mis citas de manera profesional. La plataforma es excelente tanto para doctores como pacientes.',
    rating: 5,
  },
];

export const stats = [
  { value: '2,500+', label: 'Médicos Certificados', icon: Users },
  { value: '50,000+', label: 'Consultas Realizadas', icon: FileCheck },
  { value: '4.8', label: 'Rating Promedio', icon: StarIcon },
  { value: '98%', label: 'Pacientes Satisfechos', icon: Award },
];

export const services = [
  {
    icon: Stethoscope,
    title: 'Consulta General',
    description: 'Atención médica integral para diagnóstico y tratamiento de enfermedades comunes.',
    color: 'blue',
  },
  {
    icon: Brain,
    title: 'Consulta Especializada',
    description: 'Accede a especialistas en cardiología, neurología, dermatología y más.',
    color: 'purple',
  },
  {
    icon: Smartphone,
    title: 'Telemedicina',
    description: 'Consultas en línea desde la comodidad de tu hogar, disponibles 24/7.',
    color: 'cyan',
  },
  {
    icon: Building2,
    title: 'Urgencias',
    description: 'Atención inmediata para casos urgentes con médicos de guardia.',
    color: 'rose',
  },
  {
    icon: Pill,
    title: 'Recetas Digitales',
    description: 'Recibe tus recetas médicas de forma digital, listas para surtir.',
    color: 'emerald',
  },
  {
    icon: ClipboardList,
    title: 'Historial Clínico',
    description: 'Tu expediente médico completo y seguro, accesible en cualquier momento.',
    color: 'amber',
  },
];

export const appointments = [
  {
    id: 1,
    doctor: 'Dra. María González',
    specialty: 'Cardiología',
    date: '2026-03-05',
    time: '10:00 AM',
    status: 'confirmed',
    type: 'Presencial',
  },
  {
    id: 2,
    doctor: 'Dr. Carlos Ramírez',
    specialty: 'Dermatología',
    date: '2026-03-08',
    time: '3:30 PM',
    status: 'pending',
    type: 'Telemedicina',
  },
  {
    id: 3,
    doctor: 'Dra. Ana Martínez',
    specialty: 'Pediatría',
    date: '2026-02-28',
    time: '11:00 AM',
    status: 'completed',
    type: 'Presencial',
  },
];

export const pharmacies = [
  {
    id: 1,
    name: 'Farmacia Central MedAgenda',
    address: 'Av. Winston Churchill 245, Evaristo Morales, Santo Domingo',
    phone: '+1 809-555-1234',
    hours: 'Lun-Dom: 7:00 AM - 11:00 PM',
    rating: 4.8,
    reviews: 342,
    services: ['Entrega a domicilio', 'Recetas digitales', 'Genéricos', 'Dermocosméticos'],
    available24h: false,
    hasDelivery: true,
    distance: '0.5 km',
  },
  {
    id: 2,
    name: 'Farmacia del Bienestar',
    address: 'Av. Abraham Lincoln 1200, Piantini, Santo Domingo',
    phone: '+1 809-555-5678',
    hours: '24 Horas',
    rating: 4.9,
    reviews: 521,
    services: ['24 Horas', 'Entrega express', 'Recetas digitales', 'Vacunas'],
    available24h: true,
    hasDelivery: true,
    distance: '1.2 km',
  },
  {
    id: 3,
    name: 'FarmaSalud Plus',
    address: 'Av. 27 de Febrero 800, Naco, Santo Domingo',
    phone: '+1 809-555-9012',
    hours: 'Lun-Sáb: 8:00 AM - 10:00 PM',
    rating: 4.6,
    reviews: 189,
    services: ['Genéricos', 'Suplementos', 'Equipo médico', 'Recetas digitales'],
    available24h: false,
    hasDelivery: true,
    distance: '2.1 km',
  },
  {
    id: 4,
    name: 'Farmacia Vida Sana',
    address: 'Av. Luperón 1540, Villa Mella, Santo Domingo Norte',
    phone: '+1 809-555-3456',
    hours: 'Lun-Dom: 6:00 AM - 12:00 AM',
    rating: 4.7,
    reviews: 267,
    services: ['Entrega a domicilio', 'Pruebas rápidas', 'Naturistas', 'Recetas digitales'],
    available24h: false,
    hasDelivery: true,
    distance: '3.0 km',
  },
];

export const medicines = [
  {
    id: 1,
    name: 'Amoxicilina',
    genericName: 'Amoxicilina 500mg',
    category: 'Antibiótico',
    presentation: 'Cápsulas - Caja con 21',
    price: 'RD$ 450.00',
    requiresPrescription: true,
    stock: 'Disponible',
    laboratory: 'Laboratorios Sued',
    description: 'Antibiótico de amplio espectro para infecciones bacterianas del tracto respiratorio, urinario y otitis.',
    dosage: '1 cápsula cada 8 horas',
  },
  {
    id: 2,
    name: 'Losartán',
    genericName: 'Losartán Potásico 50mg',
    category: 'Antihipertensivo',
    presentation: 'Tabletas - Caja con 30',
    price: 'RD$ 320.00',
    requiresPrescription: true,
    stock: 'Disponible',
    laboratory: 'Laboratorios Rowe',
    description: 'Antagonista de los receptores de angiotensina II para el tratamiento de la hipertensión arterial.',
    dosage: '1 tableta cada 24 horas',
  },
  {
    id: 3,
    name: 'Paracetamol',
    genericName: 'Paracetamol 500mg',
    category: 'Analgésico',
    presentation: 'Tabletas - Caja con 20',
    price: 'RD$ 120.00',
    requiresPrescription: false,
    stock: 'Disponible',
    laboratory: 'Laboratorios LAM',
    description: 'Analgésico y antipirético para el alivio del dolor leve a moderado y la fiebre.',
    dosage: '1-2 tabletas cada 6-8 horas',
  },
  {
    id: 4,
    name: 'Omeprazol',
    genericName: 'Omeprazol 20mg',
    category: 'Antiácido',
    presentation: 'Cápsulas - Caja con 14',
    price: 'RD$ 250.00',
    requiresPrescription: false,
    stock: 'Disponible',
    laboratory: 'Laboratorios López',
    description: 'Inhibidor de la bomba de protones para el tratamiento de úlceras gástricas y reflujo gastroesofágico.',
    dosage: '1 cápsula en ayunas cada 24 horas',
  },
  {
    id: 5,
    name: 'Metformina',
    genericName: 'Metformina 850mg',
    category: 'Antidiabético',
    presentation: 'Tabletas - Caja con 30',
    price: 'RD$ 200.00',
    requiresPrescription: true,
    stock: 'Disponible',
    laboratory: 'Laboratorios Sued',
    description: 'Antidiabético oral para el tratamiento de la diabetes mellitus tipo 2.',
    dosage: '1 tableta con alimentos, 2-3 veces al día',
  },
  {
    id: 6,
    name: 'Ibuprofeno',
    genericName: 'Ibuprofeno 400mg',
    category: 'Antiinflamatorio',
    presentation: 'Tabletas - Caja con 10',
    price: 'RD$ 150.00',
    requiresPrescription: false,
    stock: 'Disponible',
    laboratory: 'Laboratorios Rowe',
    description: 'Antiinflamatorio no esteroideo (AINE) para el alivio del dolor, inflamación y fiebre.',
    dosage: '1 tableta cada 8 horas después de alimentos',
  },
];

export const prescriptions = [
  {
    id: 'RX-2026-001',
    patient: 'Andrea Ruiz',
    patientAge: 34,
    doctor: 'Dra. María González',
    specialty: 'Cardiología',
    date: '2026-04-15',
    status: 'active',
    diagnosis: 'Hipertensión arterial sistémica grado I',
    medications: [
      { name: 'Losartán 50mg', dosage: '1 tableta cada 24h', duration: '30 días', notes: 'Tomar por la mañana' },
      { name: 'Aspirina 100mg', dosage: '1 tableta cada 24h', duration: '30 días', notes: 'Con alimentos' },
    ],
    notes: 'Control en 30 días. Dieta baja en sodio. Ejercicio aeróbico 30 min/día.',
    followUp: '2026-05-15',
  },
  {
    id: 'RX-2026-002',
    patient: 'Miguel Torres',
    patientAge: 28,
    doctor: 'Dr. Carlos Ramírez',
    specialty: 'Dermatología',
    date: '2026-04-14',
    status: 'active',
    diagnosis: 'Dermatitis atópica moderada',
    medications: [
      { name: 'Betametasona crema 0.05%', dosage: 'Aplicar 2 veces al día', duration: '14 días', notes: 'Capa fina en zonas afectadas' },
      { name: 'Cetirizina 10mg', dosage: '1 tableta cada 24h', duration: '30 días', notes: 'Por la noche' },
    ],
    notes: 'Usar hidratante corporal después del baño. Evitar jabones perfumados.',
    followUp: '2026-04-28',
  },
  {
    id: 'RX-2026-003',
    patient: 'Carmen Díaz',
    patientAge: 5,
    doctor: 'Dra. Ana Martínez',
    specialty: 'Pediatría',
    date: '2026-04-13',
    status: 'dispensed',
    diagnosis: 'Faringoamigdalitis bacteriana',
    medications: [
      { name: 'Amoxicilina suspensión 250mg/5ml', dosage: '5ml cada 8h', duration: '10 días', notes: 'Completar tratamiento' },
      { name: 'Paracetamol pediátrico 120mg/5ml', dosage: '5ml cada 6h si fiebre', duration: 'PRN', notes: 'Solo si temperatura >38°C' },
    ],
    notes: 'Reposo relativo. Líquidos abundantes. Regresar si fiebre persiste más de 72h.',
    followUp: '2026-04-23',
  },
];
